on:
  push:
    branches:
      - master
  pull_request:

name: Build
jobs:
  build-amd64:
    container: gcr.io/kaniko-project/executor:v1.20.0-debug 
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
    
    - name: Build and Push Image to docker registry with kaniko
      run: |
        /kaniko/executor --dockerfile="./Dockerfile" \
          --destination="rancher/hardened-containerd:test-amd64"

    # - name: Install Docker
    #   run: apt update && apt install -y docker.io && systemctl start docker

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build container image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: false
    #     tags: husseingalal/hardened-containerd:${{ env.TAG }}-amd64
    #     file: Dockerfile

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: husseingalal/hardened-containerd:${{ env.TAG }}-amd64
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      continue-on-error: true 

  build-arm64:
    container: ubuntu:latest
    runs-on: org-${{ github.repository_owner_id }}-arm64-k8s
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Docker
      run: apt update && apt install -y docker.io && systemctl start docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
    
    - name: Build container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: husseingalal/hardened-containerd:${{ env.TAG }}-arm64
        file: Dockerfile
        outputs: type=docker
        platforms: linux/arm64

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: husseingalal/hardened-containerd:${{ env.TAG }}-arm64
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      continue-on-error: true

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"
    - name: Build container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: husseingalal/hardened-containerd:${{ env.TAG }}-amd64-windows
        file: Dockerfile.windows
        outputs: type=docker
        platforms: linux/amd64

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: husseingalal/hardened-containerd:${{ env.TAG }}-amd64-windows
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      continue-on-error: true
    